EmuThread: align with co_create() and pthread_create()
Trying to compile this libretro core on my Fedora aarch64 machine
I was getting:

libretro/libretro.c:722:61: error:
passing argument 2 of ‘co_create’ from incompatible pointer type
[-Wincompatible-pointer-types]
  game_thread = co_create(65536 * sizeof(void*) * 16, EmuThreadFunction);
(redacted for clarity in this commit message)

The problem is that co_create() and pthread_create() are different
APIs. While the former expects a void (*)(void), the latter expects
a void * (*)(void *).

This commit
 * redefines EmuThreadFunction so that it matches co_create()
   where it's used, and
 * creates a new wrapping function EmuThreadWrapper matching
   the function type expected by pthread_create(), where it's used.