minizip: avoid trying to compile problematic code
Trying to compile this libretro core on my Fedora aarch64 machine
I was getting this error:

mupen64plus-core/subprojects/minizip/zip.c:1249:28:
error: assignment to
‘const long unsigned int *’ from incompatible pointer type
‘const uint32_t *’ {aka ‘const unsigned int *’}
[-Wincompatible-pointer-types]
 1249 |         zi->ci.pcrc_32_tab = get_crc_table();
      |                            ^
(redacted for clarity in this commit message)

Curiously, mupen64plus-core having the same minizip code didn't
suffer from this error. This is because there the problematic code
has been disabled by using exclusion defines NOCRYPT and NOUNCRYPT.

This commit tries to do the same for this repository.